### ISSUE TITLE
Can't build caddy due to quic error

### ISSUE THREAD

**Issue by mdegat01** [caddyserver/xcaddy#99]
I am trying to build caddy with a few custom plugins using xcaddy. My build command is this:
```
xcaddy build \
        --with github.com/mholt/caddy-ratelimit \
        --with github.com/greenpau/caddy-trace \
        --with github.com/caddy-dns/cloudflare \
        --with github.com/abiosoft/caddy-json-parse \
        --with github.com/iamd3vil/caddy_yaml_adapter \
        --with github.com/abiosoft/caddy-json-schema \
        --output caddy
```
I have been trying to do this on clean golang containers. First I tried `1.18.1-alpine3.15` then `1.17.9-alpine3.15`. In both cases the result is the same, it errors out with the following:
```
2022/04/28 03:47:53 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /go/caddy -ldflags -w -s -trimpath
# github.com/caddyserver/caddy/v2
/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.5.0/listeners.go:187:68: undefined: quic.EarlySession
2022/04/28 03:50:08 [INFO] Cleaning up temporary folder: /tmp/buildenv_2022-04-28-0346.3700484307
2022/04/28 03:50:08 [FATAL] exit status 2
```
I tried adding `XCADDY_DEBUG=1` but that didn't change the output at all so no further insight. Not really sure what to do at this point so brought it here.

**Comment by francislavoie** [comment]
Hmm, is one of the plugins you're pulling in using a newer version quic-go than Caddy is using? Caddy is still on `v0.26.0` but if something else is using `v0.27.0`, that won't work, since there was an API change.

**Comment by mdegat01** [comment]
Hm looks like [github.com/mholt/caddy-ratelimit does](https://github.com/mholt/caddy-ratelimit/blob/master/go.mod#L52). It also says it requires 2.5.0 though which is confusing since it sounds like it doesn't actually work with 2.5.0 given that requirement. I guess its a bug with that plugin then?

**Comment by mdegat01** [comment]
Ah ok, its definitely ratelimit. Removing that one from the list causes it to build without issue. I'll take my issue over to that repo then, thanks for the help!

**Comment by mholt** [comment]
Wow, I didn't see that line either. Thanks for the heads up!
