### ISSUE TITLE
Build failed at `certmagic.CleanUpOwnLocks`

### ISSUE THREAD

**Issue by gsmlg** [caddyserver/xcaddy#91]
Fail with error message
```
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
2022/03/31 11:22:53 [INFO] exec (timeout=0s): /usr/local/go/bin/go build -o /root/caddy -gcflags all=-N -l
# github.com/caddyserver/caddy/v2
/root/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.4.6/caddy.go:601:28: not enough arguments in call to certmagic.CleanUpOwnLocks
	have (*zap.Logger)
	want (context.Context, *zap.Logger)
/root/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.4.6/sigtrap_posix.go:38:31: not enough arguments in call to certmagic.CleanUpOwnLocks
	have (*zap.Logger)
	want (context.Context, *zap.Logger)
# github.com/lucas-clemente/quic-go/internal/qtls
/root/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.23.0/internal/qtls/go118.go:5:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration

```

**Comment by francislavoie** [comment]
What command did you run, exactly?

If you're building with a tagged version of Caddy, you'll need to build with Go 1.17 for now, not Go 1.18. We've fixed the issue on the master branch but it hasn't been released yet.

**Comment by gsmlg** [comment]
I install xcaddy with
`go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest`

**Comment by francislavoie** [comment]
Are you using Go 1.17 or 1.18?

**Comment by gsmlg** [comment]
I'm using `go version go1.18 linux/amd64`.

**Comment by gsmlg** [comment]
> 

Thanks to your reply.

Using `go version go1.17.8 darwin/arm64` still not working.

Change to caddy master works.
